services:
  api:
    build: .
    container_name: backup_api
    ports:
      - "8000:8000"
    env_file:
      - .env   # 👈 ensures your AWS keys and bucket name are available inside the container
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: backup_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backupdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

